% \VignetteIndexEntry{pez-intro}
%\VignettePackage{pez}
%\VignetteEngine{knitr::knitr}
\documentclass[12pt]{article}
\usepackage{amssymb,amsmath}
\usepackage{geometry}
\geometry{letterpaper}
\usepackage{graphicx}
\usepackage{url}
\usepackage{natbib}
\usepackage{color} \definecolor{dark-gray}{gray}{0.3}
\usepackage[colorlinks=true,urlcolor=dark-gray,breaklinks,citecolor=black,linkcolor=black]{hyperref}
\bibliographystyle{besjournals}
\title{An introduction to \emph{natdb}}
\author{USU Biology Nerd Group}
\date{\today}

\begin{document}
\maketitle
\tableofcontents
<<include=FALSE>>=
require(pez)
options(width=40)
@ 
\section{Preamble}
You can install \emph{natdb} by typing
\texttt{install.packages("natdb")}, and get a listing of the functions
in the package by typing \texttt{library(help=natdb)}. If you find any
bugs, or have any feature requests for the package, please use
\href{http://github.com/willpearse/natdb/issues}{the online
  tracker}. Indeed, please contribute to the package using at its
\href{http://github.com/natdb/pez/issues}{GitHub site}---help is
always welcome!

While \emph{natdb} contains much novel code, it relies heavily on the
\emph{R} ecosystem. In the development of \emph{natdb} we wrote a
great deal of code to help with \emph{fulltext} as well.

\section{Quickstart: getting some data and using it}
A short overview of how to download all the data, save it somewhere
sensible, susbet it to whatever species you want, and then use it.

\section{Details: saving data}

\section{Details: cleaning data}

\section{Details: subsetting data}


\begin{thebibliography}{6}
\providecommand{\natexlab}[1]{#1}
\providecommand{\url}[1]{\texttt{#1}}
\providecommand{\urlprefix}{URL }

\bibitem[{Ackerly(2009)Ackerly}]{Ackerly2009}
  Ackerly, D. (2009) {Conservatism and diversification of plant
    functional traits: evolutionary rates versus phylogenetic
    signal}. \emph{Proc. Natl Acad. Sci.} \textbf{106}, 19699--19706.

\bibitem[{Bryant \emph{et~al.}(2008)Bryant, Lamanna, Morlon, Kerkhoff, Enquist
  \& Green}]{Bryant2008}
Bryant, J.A., Lamanna, C., Morlon, H., Kerkhoff, A.J., Enquist, B.J. \& Green,
  J.L. (2008) Microbes on mountainsides: contrasting elevational patterns of
  bacterial and plant diversity. \emph{Proceedings of the National Academy of
  Sciences} \textbf{105}, 11505--11511,
  \urlprefix\url{http://www.pnas.org/content/105/suppl.1/11505.abstract}.

\bibitem[{Cadotte \emph{et~al.}(2013)Cadotte, Albert \& Walker}]{Cadotte2013}
  Cadotte, M., Albert, C. \& Walker, S.C. (2013)
  {The ecology of differences: assessing community assembly with trait
    and evolutionary distances}. \emph{Ecology Letters} \textbf{16}, 1234--1244.

\bibitem[{Cavender-Bares \emph{et~al.}(2004)Cavender-Bares, Ackerly,
    Baum \& Bazzaz}]{Cavender-Bares2004} Cavender-Bares, J., Ackerly,
  D.D., Baum, D.A. \& Bazzaz, F.A. (2004) {Phylogenetic overdispersion
    in Floridian oak communities}. \emph{The American Naturalist}
  \textbf{163}, 823--43.
  
\bibitem[{Cavender-Bares \& Wilczek(2003)Cavender-Bares \&
    Wilczek}]{Cavender-Bares2003} Cavender-Bares, J. \& Wilczek,
  A. (2003). Integrating micro- and macroevolutionary processes in
  community ecology. \emph{Ecology}, \textbf{84}, 592-597.
  
\bibitem[{Cavender-Bares \emph{et~al.}(2006)Cavender-Bares, Keen, \&
    Miles}]{Cavender-Bares2006} Cavender-Bares, J., A. Keen \&
  B. Miles (2006) {Phylogenetic structure of Floridian plant
    communities depends on taxonomic and spatial scale}. \emph{The
    American Naturalist} \textbf{87}, S109--S122.
  
\bibitem[{Cavender-Bares \emph{et~al.}(2009)Cavender-Bares, Kozak,
    Fine, \& Kembel}]{Cavender-Bares2009} Cavender-Bares, J., Kozak,
  K., Fine, P. \& Kembel, S. (2009). The merging of community ecology
  and phylogenetic biology. \emph{Ecology Letters}, \textbf{12},
  693-715.

\bibitem[{Evans \emph{et~al.}(2009)Evans, Smith, Flynn, \& Donoghue}]{Evans2009}
  Evans, M.E.K., Smith, S.A., Flynn, R.S. \& Donoghue, M.J. (200)
  {Climate, niche evolution, and diversification of the ``Bird-cage''
    evening primroses (Oenothera, sections Anogra and 
    Kleinia)}. \emph{Am. Nat.} \textbf{173}, 225--240.

\bibitem[{Helmus \& Ives(2012)}]{Helmus2012}
Helmus, M.R. \& Ives, A.R. (2012) Phylogenetic diversity-area curves.
  \emph{Ecology} \textbf{93}, S31--S43.

\bibitem[{Helmus \emph{et~al.}(2014) Helmus, Mercado-Silva \&
    Zanden(2014)}]{Helmus2014} Helmus, M.R., Mercado-Silva, N., \&
  Zanden, M.J.V. (2014) Subsidies to predators, apparent competition
  and the phylogenetic structure of prey communities \emph{Oceologia}
  \textbf{173}, 997--1007.

\bibitem[{Ives \& Helmus(2011)}]{Ives2011} Ives, A.R. \& Helmus,
  M.R. (2011) Generalized linear mixed models for phylogenetic
  analyses of community structure \emph{Ecological Monographs}
  \textbf{81}, 511--525.  
  
\bibitem[{Kembel \emph{et~al.}(2010)Kembel, Cowan, Helmus, Cornwell, Morlon,
  Ackerly, Blomberg \& Webb}]{Kembel2010}
Kembel, S.W., Cowan, P.D., Helmus, M.R., Cornwell, W.K., Morlon, H., Ackerly,
  D.D., Blomberg, S.P. \& Webb, C.O. (2010) Picante: R tools for integrating
  phylogenies and ecology. \emph{Bioinformatics} \textbf{26}, 1463--1464.

\bibitem[{Letten \& Cornwell(2014)Letten \& Cornwell}]{Letten2014}
  Letten, A.D. \& Cornwell, W.K. (2014) Trees, branches and (square)
  roots: why evolutionary relatedness is not linearly related to
  functional distance. \emph{Methods in Ecology and Evolution}.
  
\bibitem[{Orme \emph{et~al.}(2013)Orme, Freckleton, Thomas, Petzoldt, Fritz,
  Isaac \& Pearse}]{Orme2013}
Orme, D., Freckleton, R., Thomas, G., Petzoldt, T., Fritz, S., Isaac, N. \&
  Pearse, W.D. (2013) \emph{caper: comparative analyses of phylogenetics and
  evolution in {R}}. \urlprefix\url{http://CRAN.R-project.org/package=caper}, r
  package version 0.5.2.

\bibitem[{Pearse \emph{et~al.}(2014)Pearse, Cavender-Bares, Puvis \&
  Helmus}]{Pearse2014review}
Pearse, W.D., Cavender-Bares, J., Puvis, A. \& Helmus, M.R. (2014) Metrics and
  models of community phylogenetics. \emph{Modern Phylogenetic Comparative
  Methods and their Application in Evolutionary Biology---Concepts and
  Practice} (ed. L.Z. Garamszegi), Springer-Verlag, Berlin, Heidelberg.

\bibitem[{Rafferty \& Ives(2013)}]{Rafferty2013} Rafferty, N.E. \&
  Ives, A.R. (2013) Phylogenetic trait-based analyses of ecological
  networks \emph{Ecology} \textbf{94}, 2321--2333.

\bibitem[{Webb \emph{et~al.}(2002)Webb, Ackerly, McPeek \&
    Donoghue}]{Webb2002} Webb, C.O., Ackerly, D.D., McPeek, M.A. \&
  Donoghue M.J. (2002). Phylogenies and community ecology. \emph{Annual
  Review of Ecology and Systematics}, \textbf{33}, 475-505.

\end{thebibliography}

\end{document}
